language: java

sudo: false

jdk:
  - openjdk9

install:
  - export JAVA_TOOL_OPTIONS="-Dfile.encoding=UTF8"
  - mvn install -DskipTests -Dgpg.skip

script:
  - export JAVA_TOOL_OPTIONS="-Dfile.encoding=UTF8"
  - mvn verify -Dgpg.skip

cache:
  directories:
    - $HOME/.m2
